common:
    save_path: '.'
    load_path: ''
learner:
    learner_type: xx  # placeholder
    import_names: []  # placeholder
    use_cuda: False
    use_distributed: False
    max_iterations: 10
    unroll_len: 3
    log_freq: 1
    learning_rate: 0.001
    weight_decay: 0.0001
    data:
        batch_size: 2
        chunk_size: 2
        num_workers: 0
    hook:
#        load_ckpt:
#            name: load_ckpt
#            type: load_ckpt
#            priority: 20
#            position: before_run
#        save_ckpt_after_iter:
#            name: save_ckpt_after_iter
#            type: save_ckpt
#            priority: 40
#            position: after_iter
#            ext_args:
#                freq: 5
#        save_ckpt_after_run:
#            name: save_ckpt_after_run
#            type: save_ckpt
#            priority: 20
#            position: after_run
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 1
    communication:
        type: 'single_machine'  # ['single_machine', 'flask_fs']
        upstream_ip: 127.0.0.1
        upstream_port: 18296
        learner_ip: 127.0.0.1
        learner_port: 18295
        heartbeats_freq: 10
        send_agent_freq: 2
        send_train_info_freq: 1
        path_traj: '.'
        path_agent: '.'
        restore: False
