# This workflow will check pytest
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: algo_test

on:
  push:
    paths:
      - "ding/policy/*"
      - "ding/model/*"
      - "ding/rl_utils/*"

jobs:
  test_algotest:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: do_algotest
        env:
          WORKERS: 4
          DURATIONS: 600
        run: |
          python -m pip install .
          python -m pip install ".[test,k8s]"
          python -m pip install transformers
          ./ding/scripts/install-k8s-tools.sh
          make algotest
